# Description:
#   This script takes a whiteboard image cleans it up for easy reading
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot: whiteboard me <url>
#
# Notes:
#   Makes use of a whiteboard cleaning API
#
# Author:
#  John Hamelink <john@farmer.io>


module.exports = (robot) ->
  child = require 'child_process'
  baseApi ='http://api.o2b.ru'
  requestApi = baseApi + '/whiteboardcleaner/upload'

  # Download the image provided
  downloadFile = (url, msg) ->
    fileName = url.match(/([^\/]+$)/)[0]
    child.exec "curl #{url} > #{fileName}", (err, stdout, stderr) ->
      throw err if err
      file = { name: fileName, path: "#{fileName}" }
      uploadFile file, msg

  # Upload the downloaded image to the API
  uploadFile = (file, msg) ->
    curl = "curl #{requestApi} -H 'Origin: http://api.o2b.ru' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-GB,en;q=0.8,en-US;q=0.6' -H 'CSP: active' -H 'Cookie: sid=\"ZTk2OWI4NTJkMDNkNDRmNjhlNzRhNjQ2NmQwZWU0YjM=|143257512 1|4911e949a0ad91236047b91b92d67bb58f8692bd\"' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'User-Agent: Mozill a/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36' --form flowChunkNumber=1 --form flowFilename=#{file['name']} --form file=@#{file['path']}"
    child.exec curl, (err, stdout, stderr) ->
      throw err if err
      json = JSON.parse stdout
      # Send the resultant url back to the chat
      msg.send "Boom: #{baseApi + json['data']['url_get']}?extension=.jpg"
      deleteFile(file['path'])

  # Delete the file generated by curl
  deleteFile = (path) ->
    child.exec "rm #{path}"

  robot.respond /whiteboard me (.+)/i, (msg) ->
    msg.send "Scrub Scrub..."
    url = msg.match[1]
    tmp = downloadFile(url, msg)
