# Description:
#   This script takes a whiteboard image cleans it up for easy reading
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot: whiteboard me <url>
#
# Notes:
#   Makes use of a whiteboard cleaning API
#
# Author:
#  John Hamelink <john@farmer.io>


module.exports = (robot) ->
  child = require 'child_process'
  baseApi ='http://api.o2b.ru'
  requestApi = baseApi + '/whiteboardcleaner/upload'

  # Download the image provided
  downloadFile = (url, msg) ->
    fileName = url.match(/([^\/]+$)/)[0]
    child.exec "curl #{url} > #{fileName}", (err, stdout, stderr) ->
      throw err if err
      file = { name: fileName, path: "#{fileName}" }
      uploadFile file, msg

  # Upload the downloaded image to the API
  uploadFile = (file, msg) ->
    curl = "curl -q --form flowFilename=#{file['name']} --form file=@#{file['path']} #{requestApi}"
    child.exec curl, (err, stdout, stderr) ->
      throw err if err
      json = JSON.parse stdout
      # Send the resultant url back to the chat
      msg.send "Boom: #{baseApi + json['data']['url_get']}?extension=.jpg"
      deleteFile(file['path'])

  # Delete the file generated by curl
  deleteFile = (path) ->
    child.exec "rm #{path}"

  robot.respond /whiteboard me (.+)/i, (msg) ->
    msg.send "Scrub Scrub..."
    url = msg.match[1]
    tmp = downloadFile(url, msg)
